### ISSUE TITLE
Try to avoid using Context Initializers

### ISSUE THREAD

**Issue by SergeyKanzhelev** [fidmor89/SLAB_AppInsights#3] opened 2015-07-06 14:37 UTC
The drawback of using context initializers is that they may not be properly initialized for all data colleciton NuGets. Use telemetry initializers instead. See this [blog post](http://apmtips.com/blog/2015/06/09/do-not-use-context-initializers/) for details.

**Comment by fidmor89** [comment] 2015-07-09 00:26
Issue was solved with commits: a06d72697a40cd020a9bafee1df953bafc3631b7, 9e96e5609e77ab8cf1c291e3202c075d428ba06c, cbaac7f71e7daf89b85c664a338b9bad64773a3f and 3a6c22235dc3029644c83b679080a7e95b87db4f. @chepix10 please check with the test project to make sure its working as intended before closing the issue.

**Comment by chepix10** [comment] 2015-07-15 00:52
@fidmor89 We made test with @chirislash and everything was successful. So we're closing the issue. Regards.

**Closed as completed by chepix10** 2015-07-15 00:52 UTC
Labels: enhancement, help wanted
